`timescale 1ns / 1ps
module topModule(
    input clk,
    output [31:0] DUMMY_BUFF,
    output [31:0] DUMMY_DATA_READ,
	output [31:0] DUMMY_ALU_OUT,
    output [31:0] DUMMY_OUT_FROM_DATA,
    output DUMMY_WRITE_ENABLE
    );

    // FETCH STAGE
    wire [31:0] FETCH_TO_INST_BUFFER;
    wire [31:0] INST_BUFFER_OUT;
    wire [7:0] JUMPER_FROM_BRANCH;
    wire [7:0] FIRST_PC_IN, FIRST_PC_OUT, SECOND_PC_OUT;

    // CONTROL UNIT WIRES
    wire [5:0] CONTROL_IN;
    // Raw signals from Control Unit
    wire REG_DST_IN, BRANCH_IN, MEM_READ_IN, MEM_TO_REG_IN, MEM_WRITE_IN, ALU_SRC_IN, REG_WRITE_IN;
    wire [1:0] ALU_OP_IN;

    // DECODE STAGE WIRES
    wire [14:0] DECODE_IN;
    wire [31:0] DATA_READ_MEM_1, DATA_READ_MEM_2;
    wire [4:0] DEST_ADDR_ID_EX;

    // ID/EX BUFFER OUTPUTS
    wire [31:0] BUFFER_TO_ALU_1, BUFFER_TO_ALU_2, EXTENDED_TO_ALU;
    wire [4:0] DEST_ADDR_EX_MEM;
    // Control signals exiting ID/EX
    wire BRANCH_EX, MEM_READ_EX, MEM_TO_REG_EX, MEM_WRITE_EX, ALU_SRC_EX, REG_WRITE_EX; 
    wire [1:0] ALU_OP_EX;

    // SIGNAL EXTEND
    wire [15:0] SIGNAL_EXTEND_IN;
    wire [31:0] EXTENDED_SIGNAL;

    // ALU CONTROL
    wire [5:0] ALU_CONTROL_DATA;
    wire [3:0] OUT_ALU_CONTROL;

    // EXECUTE STAGE
    wire ZERO_CONDITION_ALU_OUT;
    wire [31:0] RESPONSE_ALU;

    // EX/MEM BUFFER OUTPUTS
    wire [31:0] ALU_RESULT_MEM, STORE_DATA_MEM;
    wire [4:0] DEST_ADDR_MEM_WB;
    wire MEM_WRITE_MEM, MEM_READ_MEM, MEM_TO_REG_MEM, REG_WRITE_MEM;

    // MEMORY STAGE
    wire [31:0] MEM_ACCESS_OUT_TO_BUFFER;

    // MEM/WB BUFFER OUTPUTS
    wire [31:0] DATA_ROLLBACK_TO_REG;
    wire [4:0] FINAL_WRITE_ADDR;
    wire FINAL_REG_WRITE_ENABLE;
    wire JUMP_FLAG;



    FETCH FETCH_LOOP(
        .clk(clk),
        .PC_JUMPER(JUMPER_FROM_BRANCH),
        .PC_JUMP_FLAG(JUMP_FLAG),
        .FETCH_OUT(FETCH_TO_INST_BUFFER),
        .PC_COUNTER_OUT(FIRST_PC_IN)
    );
    
    instBuffer_behavioral INST_BUFFER(
        .clk(clk),
        .PC_COUNTER_FIRST_IN(FIRST_PC_IN),
        .DATA_IN(FETCH_TO_INST_BUFFER),
        .DATA_OUT(INST_BUFFER_OUT),
        .PC_COUNTER_FIRST_OUT(FIRST_PC_OUT)
    );

    aluControl_behavioral CONTROL(
        .FULL_IN(CONTROL_IN),
        .REG_DST(REG_DST_IN),
        .BRANCH(BRANCH_IN),
        .MEM_READ(MEM_READ_IN),
        .MEM_TO_REG(MEM_TO_REG_IN),
        .MEM_WRITE(MEM_WRITE_IN),
        .ALU_SRC(ALU_SRC_IN),
        .REG_WRITE(REG_WRITE_IN),
        .ALU_OP(ALU_OP_IN)
    );
    
    DECODE DECODE_LOOP(
        .clk(clk),
        .FULL_DATA(DECODE_IN),
        .REG_DST_DECODE(REG_DST_IN), 
        .REG_WRITE_DECODE(FINAL_REG_WRITE_ENABLE),
        .WRITE_ADDR_FROM_WB(FINAL_WRITE_ADDR),
        .DATA_IN_FROM_MEMORY(DATA_ROLLBACK_TO_REG),
        .DATA_READ_1(DATA_READ_MEM_1),
        .DATA_READ_2(DATA_READ_MEM_2),
        .CHOSEN_DEST_ADDR(DEST_ADDR_ID_EX)
    );
    
    signalExtend_behavioral SIGNAL_EXTEND(
        .UNEXTENDED(SIGNAL_EXTEND_IN),
        .EXTENDED(EXTENDED_SIGNAL)
    );
    
    aluBuffer_behavioral ALU_BUFFER(
        .clk(clk),
        .DATA_IN_1(DATA_READ_MEM_1),
        .DATA_IN_2(DATA_READ_MEM_2),
        .EXTENDED_IN(EXTENDED_SIGNAL),
        .DEST_ADDR_IN(DEST_ADDR_ID_EX),
        .PC_COUNTER_SECOND_IN(FIRST_PC_OUT),
        .BRANCH_BUFF(BRANCH_IN),
        .MEM_READ_BUFF(MEM_READ_IN),
        .MEM_TO_REG_BUFF(MEM_TO_REG_IN),
        .ALU_OP_BUFF(ALU_OP_IN),
        .MEM_WRITE_BUFF(MEM_WRITE_IN),
        .ALU_SRC_BUFF(ALU_SRC_IN),
        .REG_WRITE_BUFF(REG_WRITE_IN),
        .DATA_OUT_1(BUFFER_TO_ALU_1),
        .DATA_OUT_2(BUFFER_TO_ALU_2),
        .EXTENDED_OUT(EXTENDED_TO_ALU),
        .DEST_ADDR_OUT(DEST_ADDR_EX_MEM),
        .PC_COUNTER_SECOND_OUT(SECOND_PC_OUT),
        .BRANCH_BUFF_OUT(BRANCH_EX),
        .MEM_READ_BUFF_OUT(MEM_READ_EX),
        .MEM_TO_REG_BUFF_OUT(MEM_TO_REG_EX),
        .ALU_OP_BUFF_OUT(ALU_OP_EX),
        .MEM_WRITE_BUFF_OUT(MEM_WRITE_EX),
        .ALU_SRC_BUFF_OUT(ALU_SRC_EX),
        .REG_WRITE_BUFF_OUT(REG_WRITE_EX)
    );

    aluControl_beh ALU_CONTROL(
        .OP_CONTROL(ALU_OP_EX),
        .FUNCTION(ALU_CONTROL_DATA),
        .ALU_CONTROL_OUT(OUT_ALU_CONTROL)
    );

    EXECUTE EXECUTE_LOOP(
        .ALU_SRC_TO_MUX(ALU_SRC_EX),
        .EXTENDED_SIGNAL_TO_MUX(EXTENDED_TO_ALU),
        .REG_DATA_1(BUFFER_TO_ALU_1),
        .REG_DATA_TO_MUX_2(BUFFER_TO_ALU_2),
        .ALU_CONTROL_IN(OUT_ALU_CONTROL),
        .OP_CODE(ALU_OP_EX),
        .ZERO_CONDITION_ALU(ZERO_CONDITION_ALU_OUT),
        .VALUE_ALU_OUT(RESPONSE_ALU)
    );

    dataBuffer_behavioral DATA_BUFFER(
        .clk(clk),
        .VALUE_BUFFER_IN(RESPONSE_ALU),
        .READ_DATA_2_IN(BUFFER_TO_ALU_2), 
        .DEST_ADDR_IN(DEST_ADDR_EX_MEM),
        .MEM_WRITE_ACCESS_BUFF(MEM_WRITE_EX),
        .MEM_READ_ACCESS_BUFF(MEM_READ_EX),
        .MEM_TO_REG_ACCESS_BUFF(MEM_TO_REG_EX),
        .REG_WRITE_BUFF(REG_WRITE_EX),
        .VALUE_BUFFER_OUT(ALU_RESULT_MEM),
        .READ_DATA_2_OUT(STORE_DATA_MEM),
        .DEST_ADDR_OUT(DEST_ADDR_MEM_WB),
        .MEM_WRITE_ACCESS_BUFF_OUT(MEM_WRITE_MEM),
        .MEM_READ_ACCESS_BUFF_OUT(MEM_READ_MEM),
        .MEM_TO_REG_ACCESS_BUFF_OUT(MEM_TO_REG_MEM),
        .REG_WRITE_BUFF_OUT(REG_WRITE_MEM)
    );

    MEMORY_ACCESS MEMORY(
        .clk(clk),
        .ADDRESS_MEMORY_ACCESS(ALU_RESULT_MEM),
        .READ_DATA_2_ACCESS(STORE_DATA_MEM),
        .MEM_WRITE_ACCESS(MEM_WRITE_MEM),
        .MEM_READ_ACCESS(MEM_READ_MEM),
        .MEM_TO_REG_ACCESS(MEM_TO_REG_MEM),
        .OUT_MUX_ACCESS(MEM_ACCESS_OUT_TO_BUFFER)
    );

    memRollBackBuffer_behavioral ROLLBACK_BUFFER(
        .clk(clk),
        .MEMORY_TO_BUFFER(MEM_ACCESS_OUT_TO_BUFFER),
        .DEST_ADDR_IN(DEST_ADDR_MEM_WB),
        .REG_WRITE_IN(REG_WRITE_MEM),
        .MEMORY_TO_REG(DATA_ROLLBACK_TO_REG),
        .DEST_ADDR_OUT(FINAL_WRITE_ADDR),
        .REG_WRITE_OUT(FINAL_REG_WRITE_ENABLE)
    );

    WRITE_BACK BRANCH_UNIT(
        .EXTENDED_UNSHIFT_TOP(EXTENDED_TO_ALU),
        .PC_COUNTER_ADDR_TOP(SECOND_PC_OUT),
        .BRANCH_TOP(BRANCH_EX),
        .ZERO_CONDITION_TOP(ZERO_CONDITION_ALU_OUT),
        .JUMP(JUMPER_FROM_BRANCH),
        .BRANCH_DECISION(JUMP_FLAG)
    );
	 
    assign CONTROL_IN = INST_BUFFER_OUT[31:26];
    assign DECODE_IN = INST_BUFFER_OUT[25:11];
    assign SIGNAL_EXTEND_IN = INST_BUFFER_OUT[15:0];
    assign ALU_CONTROL_DATA = INST_BUFFER_OUT[5:0];

    assign DUMMY_BUFF = DATA_ROLLBACK_TO_REG | {27'b0, FINAL_WRITE_ADDR};
    assign DUMMY_DATA_READ = DATA_READ_MEM_1;
    assign DUMMY_ALU_OUT = ALU_RESULT_MEM;
    assign DUMMY_OUT_FROM_DATA = MEM_ACCESS_OUT_TO_BUFFER;
    assign DUMMY_WRITE_ENABLE = REG_WRITE_MEM;
//slash
endmodule